"""
detection.py — the two detection signals, confidence scoring, and label mapping.

Signal 1 (LLM / Groq): semantic. Judges holistically whether text reads as AI-generated.
Signal 2 (stylometrics): structural. Measures statistical fingerprints of how text is built.
The two are combined into a single calibrated confidence score = P(AI-generated).
"""

import os
import re
import json
import statistics

from groq import Groq

# --- configuration ---------------------------------------------------------

GROQ_MODEL = "llama-3.3-70b-versatile"

# Signal weighting: the LLM is the stronger holistic signal, so it carries more weight;
# stylometrics is an independent structural cross-check.
LLM_WEIGHT = 0.6
STYLO_WEIGHT = 0.4

# Asymmetric thresholds. The AI cutoff sits 0.15 above the neutral midpoint (0.5); the
# human cutoff only 0.10 below it. We deliberately require MORE evidence to accuse than to
# clear, so a borderline case defaults to the less-harmful outcome — the false-positive
# asymmetry made concrete.
HUMAN_MAX = 0.40   # confidence < 0.40            -> likely_human
AI_MIN = 0.65      # confidence > 0.65            -> likely_ai
                   # 0.40 <= confidence <= 0.65   -> uncertain

# Exact transparency-label text for each variant (also documented verbatim in the README).
LABELS = {
    "likely_human": (
        "\u2713 Likely human-written. Our analysis found writing patterns consistent with "
        "human authorship, and no strong signals of AI generation. This is an automated "
        "estimate, not a guarantee."
    ),
    "uncertain": (
        "\u25cf Origin uncertain. Our analysis was inconclusive \u2014 this content shows a "
        "mix of signals, and we can't determine with confidence whether it was written by a "
        "person or generated by AI. Please treat this result as informational only."
    ),
    "likely_ai": (
        "\u26a0 Signals consistent with AI generation. Our analysis found patterns often "
        "associated with AI-generated text. This is not a definitive judgment, and automated "
        "detection can be wrong \u2014 especially for formal or non-native-English writing. "
        "If you wrote this yourself, you can appeal."
    ),
}

_client = None


def _get_client():
    """Lazily construct the Groq client so importing this module never requires a key."""
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client


# --- Signal 1: LLM classification (semantic) -------------------------------

def llm_signal(text):
    """
    Ask Groq to estimate the probability the text is AI-generated.
    Returns a float in [0, 1] (= P(AI)).

    Degrades gracefully: if the API call or JSON parse fails, returns a neutral 0.5 so a
    transient error can't crash a submission. (We would surface/monitor this in production.)
    """
    prompt = (
        "You are an AI-text-detection assistant. Assess whether the following text was "
        "written by a human or generated by an AI language model. Consider coherence, "
        "register, and the evenness typical of AI prose. Respond ONLY with strict JSON of "
        "the form {\"ai_probability\": <float 0.0-1.0>, \"reasoning\": \"<one sentence>\"}, "
        "where ai_probability is your estimated probability the text is AI-generated.\n\n"
        f"TEXT:\n{text}"
    )
    try:
        resp = _get_client().chat.completions.create(
            model=GROQ_MODEL,
            messages=[{"role": "user", "content": prompt}],
            temperature=0,
            response_format={"type": "json_object"},
        )
        data = json.loads(resp.choices[0].message.content)
        score = float(data.get("ai_probability", 0.5))
        return max(0.0, min(1.0, score))
    except Exception:
        return 0.5


# --- Signal 2: stylometric heuristics (structural) -------------------------

_SENT_SPLIT = re.compile(r"[.!?]+")
_WORD = re.compile(r"[A-Za-z']+")
_PUNCT_MARKS = [",", ".", ";", ":", "-", "\u2014", "(", ")", "!", "?", '"', "'", "\u2026"]


def _clamp(x):
    return max(0.0, min(1.0, x))


def stylo_signal(text):
    """
    Combine three structural metrics into one 'AI-likeness' score in [0, 1] (= P(AI)).

      * sentence-length variance ("burstiness"): low variance -> more AI-like
      * type-token ratio (lexical diversity):   low diversity -> more AI-like
      * punctuation variety:                     few distinct marks -> more AI-like

    Returns (stylo_score, details). For very short texts (< 3 sentences) we cannot measure
    variance reliably, so we return a neutral 0.5 and flag low reliability.
    """
    sentences = [s.strip() for s in _SENT_SPLIT.split(text) if s.strip()]
    words = _WORD.findall(text.lower())

    if len(sentences) < 3 or len(words) < 15:
        return 0.5, {"reliable": False, "note": "text too short for reliable stylometrics"}

    # Burstiness: std dev of sentence lengths (in words). ~0 -> AI, >=8 -> human.
    lengths = [len(_WORD.findall(s)) for s in sentences]
    std = statistics.pstdev(lengths) if len(lengths) > 1 else 0.0
    ai_burst = _clamp(1.0 - std / 8.0)

    # Type-token ratio over a capped window (TTR is length-sensitive). ttr>=0.75 -> human,
    # ttr<=0.40 -> AI.
    window = words[:200]
    ttr = len(set(window)) / len(window)
    ai_ttr = _clamp((0.75 - ttr) / 0.35)

    # Punctuation variety: 1 distinct mark -> AI, 5+ -> human.
    distinct = sum(1 for m in _PUNCT_MARKS if m in text)
    ai_punct = _clamp(1.0 - (distinct - 1) / 4.0)

    score = (ai_burst + ai_ttr + ai_punct) / 3.0
    details = {
        "reliable": True,
        "sentence_length_std": round(std, 2),
        "type_token_ratio": round(ttr, 3),
        "distinct_punctuation": distinct,
        "ai_burstiness": round(ai_burst, 3),
        "ai_ttr": round(ai_ttr, 3),
        "ai_punctuation": round(ai_punct, 3),
    }
    return round(score, 4), details


# --- confidence scoring + label mapping ------------------------------------

def score_text(text):
    """
    Run both signals, combine into a single confidence = P(AI-generated), and map to a
    transparency label. Returns a dict with everything the endpoint and audit log need.
    """
    llm = llm_signal(text)
    stylo, stylo_details = stylo_signal(text)

    confidence = round(LLM_WEIGHT * llm + STYLO_WEIGHT * stylo, 4)

    if confidence < HUMAN_MAX:
        attribution = "likely_human"
    elif confidence > AI_MIN:
        attribution = "likely_ai"
    else:
        attribution = "uncertain"

    return {
        "attribution": attribution,
        "confidence": confidence,
        "label": LABELS[attribution],
        "llm_score": round(llm, 4),
        "stylo_score": stylo,
        "stylo_details": stylo_details,
    }
